sudo: required

services:
  - docker

env:
  - JAVA_URL="http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.tar.gz"
  - JAVA_FILE="jre-8u60-linux-x64.tar.gz"
  - JAVA_FILE_SHA256="899d9f09d7c1621a5cce184444b0ba97a8b0391bd85b624ea29f81a759764c55"

before_install:
  - docker pull sample/java-builder
  - mkdir java
  - curl -j -L -H "Cookie: oraclelicense=accept-securebackup-cookie" $JAVA_URL > java/$JAVA_FILE
  - echo "$JAVA_FILE_SHA256 java/$JAVA_FILE" > shasum
  - shasum -c ./shasum

script:
  - docker run -v $PWD/java:/java -v $PWD/target:/target -it --rm sample/java-builder $JAVA_FILE
